name: CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: pip cache
        uses: actions/cache@v1
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('setup.cfg') }}
          restore-keys: |
            ${{ runner.os }}-pip
      - run: pip install -e .[test]
      - name: mypy cache
        uses: actions/cache@v1
        with:
          path: .mypy_cache
          key: ${{ runner.os }}-mypy-${{ hashFiles('setup.cfg') }}
          restore-keys: |
            ${{ runner.os }}-mypy
      - run: make lint
      - run: make test
